apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachine-{{ include "homa.prefix" . }}
  labels:
    app.kubernetes.io/name: {{ include "homa.name" . }}
    helm.sh/chart: {{ include "homa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type:  {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
      - image: timjdfletcher/samba-timemachine:timemachine-v2.3
        name: timemachine-container
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: "Europe/Berlin"
        volumeMounts:
        - mountPath: /backups
          name: timemachine-pvc
          subPath: ./
      volumes:
      - name: timemachine-pvc
        persistentVolumeClaim:
          claimName: timemachine-pvc
