apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8000Gi
