substitutions:
  plug_name: ws2813_1
  mqtt: !secret mqtt
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m
  #includes:
  #  - udp-context.h
  #  - lifx-light.h

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
#api:

ota:

mqtt:
   broker: ${mqtt}
#  port: 1883

  #light:
  #- platform: neopixelbus
  #  default_transition_length: 1s
  #  type: GRBW
  #pin: GPIO2
    #  variant: SK6812
    #method: ESP8266_UART1
    #  num_leds: 52
    #name: "leds"
    #id: "leds"
  #   # ...
  #   effects:
  #     - addressable_fireworks:
  #     - addressable_rainbow:
  #     - addressable_twinkle:
  #     - addressable_color_wipe:
  #     - addressable_color_wipe:
  #         name: Color Wipe Effect With Custom Values
  #         colors:
  #           - red: 100%
  #             green: 100%
  #             blue: 100%
  #             num_leds: 1
  #           - red: 0%
  #             green: 0%
  #             blue: 0%
  #             num_leds: 1
  #         add_led_interval: 100ms
  #         reverse: False

sensor:
  - platform: uptime
    name: uptime
  
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

#light:
#  - platform: fastled_clockless
#    chipset: SK6812
#    pin: GPIO2
#    num_leds: 300
#    rgb_order: GRB
#    name: "strip"
#    effects:
#      - addressable_rainbow:
#      - addressable_fireworks:
#      - addressable_fireworks:
#          name: Fireworks Effect With Custom Values
#          update_interval: 32ms
#          spark_probability: 10%
#          use_random_color: false
#          fade_out_rate: 120
light:
  - platform: neopixelbus
    default_transition_length: 1s
    type: GRBW
    pin: GPIO2
    variant: SK6812
    method: ESP8266_UART1
    num_leds: 300
    name: "leds"
    id: "leds"
