substitutions:
  plug_name: spiegel
  mqtt: !secret mqtt
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: uptime
    name: uptime
  
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

light:
  - platform: monochromatic
    name: "Spiegel"
    output: output_component1

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO2

