substitutions:
  device_name: sw-h20
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: ${mqtt}
#  discovery_unique_id_generator: mac
#  port: 1883

sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: blau
    name: "unten-links"
    pin: D5

  - platform: gpio
    id: gelb
    name: "unten-rechts"
    pin: D6

  - platform: gpio
    id: gruen
    name: "oben-rechts"
    pin: D7

  - platform: gpio
    id: weiss
    name: "oben-links"
    pin: D0
#
