substitutions:
  device_name: sw-h05
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
logger:
api:
ota:
mqtt:
  broker: ${mqtt}
sensor:
- platform: uptime
  name: uptime
- platform: wifi_signal
  name: Wi-Fi_Signal
  update_interval: 60s
binary_sensor:
- platform: gpio
  id: blau
  name: unten-links
  pin:
    number: D5
    inverted: true
- platform: gpio
  id: gelb
  name: unten-rechts
  pin:
    number: D6
    inverted: true
- platform: gpio
  id: gruen
  name: oben-rechts
  pin:
    number: D7
    inverted: true
- platform: gpio
  id: weiss
  name: oben-links
  pin:
    number: D0
    inverted: true
