esphome:
  name: "bench32"

esp32:
  board: m5stack-atom
  framework:
    type: arduino


#esp8266:
#  board: esp01_1m
#  framework:
#    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-93B595"
    password: "pBgkRyRdCWja"

captive_portal:
    
light:
  - platform: fastled_spi
    chipset: P9813
    data_pin: GPIO21
    clock_pin: GPIO25
    num_leds: 12                                                                                                                                                                                                                                                                               
    rgb_order: RGB
    name: "SuperBox"                                                         

#  - platform: neopixelbus
#    type: GRB
#    variant: P9813
#    data_pin: GPIO21
#    clock_pin: GPIO5
#    num_leds: 36
##    name: SuperNeo
                                                


                                                    