substitutions:
  plug_name: dose5
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  current_res: "0.00221"
  voltage_div: "955"
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883
  
#time:
#  - platform: homeassistant
#    id: homeassistant_time
time:
  - platform: sntp

binary_sensor:
  - platform: gpio
    name: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
  - platform: status
    name: state

switch:
  - platform: gpio
    id: relay
    name: relay
    icon: mdi:power-socket-eu
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    name: led_blue
    icon: mdi:led-on
    pin: 
      number: GPIO02
      inverted: True

#  - platform: gpio
#    id: red_led
#    name: led_red
#    icon: mdi:led-on
#    pin: 
#      number: GPIO03
#      inverted: True

sensor:
#  - platform: hlw8012
#    sel_pin:
#      number: GPIO13
#      inverted: True
#    cf_pin: GPIO04
#    cf1_pin: GPIO05
#    current_resistor: ${current_res}
#    voltage_divider: ${voltage_div}
#    current:
#      name: amperage
#      icon: mdi:current-ac
#      unit_of_measurement: A
#    voltage:
#      name: voltage
#      icon: mdi:flash-circle
#      unit_of_measurement: V
#    power:
#      name: wattage
#      icon: mdi:flash-outline
#      unit_of_measurement: W
#      id: wattage
#    change_mode_every: 8
#    update_interval: 10s

#  - platform: total_daily_energy
#    name: Total Daily Energy
#    icon: mdi:circle-slice-3
#    power_id: wattage
#    filters:
      # Multiplication factor from W to kW is 0.001
#      - multiply: 0.001
#    unit_of_measurement: kWh
      
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: uptime

  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: firmware_version
