substitutions:
  plug_name: hiled_1
  mqtt: !secret mqtt
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01
  #includes:
  #  - udp-context.h
  #  - lifx-light.h

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: ${mqtt}
  discovery_unique_id_generator: mac
#  port: 1883


output:
  - platform: esp8266_pwm
    pin: GPIO2
    frequency: 1000 Hz
    id: pwm_output

# Example usage in a light
light:
  - platform: monochromatic
    output: pwm_output
    name: "hiled_1"

