substitutions:
  device_name: sw-test
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: ${mqtt}
  discovery_unique_id_generator: mac
#  port: 1883

sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: "_D8"
    name: "oben-links"
    pin: 
      number: D8
      mode:
        input: true
        pullup: false
    on_multi_click:
    - timing:
         - ON for 0.2s to 1s
         - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/PRESS_SHORT
            payload: "PRESS_SHORT"


  - platform: gpio
    id: "_D7"
    name: "unten-rechts"
    pin: 
      number: D7
      mode:
        input: true
        pullup: false
#    on_multi_click:
#    - timing:
#        - ON for 0.2s to 1s
#        - OFF for at least 0.3s
#      then:
#        # - logger.log: "Oben-Links Single Long Clicked"
#        - mqtt.publish:
#            topic: ${device_name}/binary_sensor/unten-rechts/PRESS_LONG
##            payload: "PRESS_LONG"
#    - timing:
#        - ON for at most 0.2s
#        - OFF for at least 0.1s
#      then:
#        # - logger.log: "Open-Links Single Short Clicked"
#        - mqtt.publish:
#            topic: ${device_name}/binary_sensor/unten-rechts/PRESS_SHORT
#            payload: "PRESS_SHORT"

  - platform: gpio
    id: "_D5"
    name: "oben-rechts"
    pin:
      number: D5
      mode:
        input: true
        pullup: false
    on_multi_click:
    - timing:
        - ON for 0.2s to 1s
        - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
           topic: ${device_name}/binary_sensor/oben-rechts/PRESS_SHORT
           payload: "PRESS_SHORT"

  - platform: gpio
    id: "_D6"
    name: "unten-links"
    pin:
      number: D6
      mode:
        input: true
        pullup: false
    on_multi_click:
    - timing:
        - ON for 0.2s to 1s
        - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/PRESS_SHORT
            payload: "PRESS_SHORT"
