substitutions:
  plug_name: h801_3
  mqtt: !secret mqtt
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m
  #includes:
  #  - udp-context.h
  #  - lifx-light.h

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: ${mqtt}
#  port: 1883

  #light:
  #- platform: neopixelbus
  #  default_transition_length: 1s
  #  type: GRBW
  #pin: GPIO2
    #  variant: SK6812
    #method: ESP8266_UART1
    #  num_leds: 52
    #name: "leds"
    #id: "leds"
  #   # ...
  #   effects:
  #     - addressable_fireworks:
  #     - addressable_rainbow:
  #     - addressable_twinkle:
  #     - addressable_color_wipe:
  #     - addressable_color_wipe:
  #         name: Color Wipe Effect With Custom Values
  #         colors:
  #           - red: 100%
  #             green: 100%
  #             blue: 100%
  #             num_leds: 1
  #           - red: 0%
  #             green: 0%
  #             blue: 0%
  #             num_leds: 1
  #         add_led_interval: 100ms
  #         reverse: False

sensor:
  - platform: uptime
    name: uptime
  
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s


output:
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_cw
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_ww


light:
  - platform: cwww
    name: "oben"
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true

  - platform: cwww
    name: "unten"
    cold_white: pwm_r
    warm_white: pwm_g
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true

