apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-{{ include "homa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "homa.fullname" . }}
    helm.sh/chart: {{ include "homa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type:  {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homa.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        run: {{ include "homa.fullname" . }}
        app.kubernetes.io/name: {{ include "homa.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
      - name: tailscale-meno
        image: fastandfearless/tailscale:latest
        securityContext:
          privileged: true
        command: [ "tailscaled", "--tun=tailscale0", "--port=6767"]
        volumeMounts:
        - mountPath: /var/lib/tailscale
          name: homa-pvc
          subPath: tailscaled-meno
      - name: tailscale-malte
        image: fastandfearless/tailscale:latest
        securityContext:
          privileged: true
        command: [ "tailscaled", "--tun=tailscale1", "--port=6768"]
        volumeMounts:
        - mountPath: /var/lib/tailscale
          name: homa-pvc
          subPath: tailscaled-malte

      volumes:
      - name: homa-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.pvcClaim }}
