substitutions:
  plug_name: decke_kueche
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883

light:
  - platform: rgbww
    name: "Decke Kueche"
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO16
  - platform: esp8266_pwm
    # fine
    id: output_green
    pin: GPIO05
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO04
  - platform: esp8266_pwm
    id: output_cw
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_ww
    pin: GPIO14
    
sensor:
  - platform: uptime
    name: uptime

