substitutions:
  plug_name: dose6
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt
  current_res: "0.00221"
  voltage_div: "955"
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: ${mqtt}
  discovery_unique_id_generator: mac
#  port: 1883
  
#time:
#  - platform: homeassistant
#    id: homeassistant_time
time:
  - platform: sntp

binary_sensor:
  - platform: gpio
    name: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: lava_dose
  - platform: status
    name: state

output:
  - platform: gpio
    pin: GPIO15
    id: relay_1

light:
  - platform: binary
    name: "Lava"
    id: lava_dose
    output: relay_1

switch:

  - platform: gpio
    id: blue_led
    name: led_blue
    icon: mdi:led-on
    pin: 
      number: GPIO02
      inverted: True

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: uptime

  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: firmware_version
