substitutions:
  plug_name: lifx_test
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini
  
  includes:
    - udp-context.h
    - lifx-light.h

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
#api:

ota:

time:
  - platform: sntp
    id: sntp_time

mqtt:
  broker: 192.168.202.4
#  port: 1883

# light:
#   #  - platform: neopixelbus
#   #  default_transition_length: 1s
#   #  type: GRBW
#   #  pin: GPIO1
#   #  variant: SK6812
#   #  method: ESP8266_UART0
#   #  num_leds: 22
#   #  name: "schrank-r"
#   #  id: "schrank_r"
#   #  # ...
#   #  #effects:
#   #  #  - addressable_fireworks:
#   #  #  - addressable_rainbow:
#       
#   - platform: neopixelbus
#     default_transition_length: 1s
#     type: GRBW
#     pin: GPIO2
#     variant: SK6812
#     method: ESP8266_UART1
#     num_leds: 52
#     name: "leds"
#     id: "leds"
#     # ...
#     effects:
#       - addressable_fireworks:
#       - addressable_rainbow:
#       - addressable_twinkle:
#       - addressable_color_wipe:
#       - addressable_color_wipe:
#           name: Color Wipe Effect With Custom Values
#           colors:
#             - red: 100%
#               green: 100%
#               blue: 100%
#               num_leds: 1
#             - red: 0%
#               green: 0%
#               blue: 0%
#               num_leds: 1
#           add_led_interval: 100ms
#           reverse: False
# 

    
sensor:
  - platform: custom
    lambda: |-
      auto my_lifx_light = new LifxLight();
      App.register_component(my_lifx_light);
      return {my_lifx_light};
    sensors:
      name: "MyLifxLight"

  - platform: uptime
    name: uptime
    
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
