substitutions:
  device_name: sw_01
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883

sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: gpio14
    name: "oben-links"
    pin: GPIO14
    on_multi_click:
    - timing:
         - ON for 0.2s to 1s
         - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/PRESS_SHORT
            payload: "PRESS_SHORT"


  - platform: gpio
    id: gpio12
    name: "unten-rechts"
    pin: GPIO12
    on_multi_click:
    - timing:
        - ON for 0.2s to 1s
        - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/PRESS_SHORT
            payload: "PRESS_SHORT"

  - platform: gpio
    id: gpio13
    name: "oben-rechts"
    pin: GPIO13
    on_multi_click:
    - timing:
        - ON for 0.2s to 1s
        - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
           topic: ${device_name}/binary_sensor/oben-rechts/PRESS_SHORT
           payload: "PRESS_SHORT"

  - platform: gpio
    id: gpio16
    name: "unten-links"
    pin: GPIO16
    on_multi_click:
    - timing:
        - ON for 0.2s to 1s
        - OFF for at least 0.3s
      then:
        # - logger.log: "Oben-Links Single Long Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/PRESS_LONG
            payload: "PRESS_LONG"
    - timing:
        - ON for at most 0.2s
        - OFF for at least 0.1s
      then:
        # - logger.log: "Open-Links Single Short Clicked"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/PRESS_SHORT
            payload: "PRESS_SHORT"

